# NumPy

Libreria base su cui hanno costruito ```pandas``` e ```sklearn``` ad esempio

Da qui in poi seguiremo il tutorial:
https://jakevdp.github.io/PythonDataScienceHandbook/

In [1]:
#NUMPY
import numpy as np

In [4]:
np.__version__

'1.19.2'

In [ ]:
dir(np)

I docs online delle librerie si dividono di solito in tutorial (introduttivi) e API (doc tecnici)
https://numpy.org/

In [6]:
import random

In [ ]:
random.random?

Facciamo delle moltiplicazioni, tipo tantissime

In [7]:
cicli=10**6
lista1=[random.random() for i in range(cicli) ]
lista2=[random.random() for i in range(cicli) ]

In [ ]:
%timeit prodotto=[lista1[i]*lista2[i] for i in range(cicli)]

Usiamo ora numpy per lo stesso calcolo, quindi porto le liste in ```numpy```

In [9]:
arr1_np,arr2_np=np.array(lista1),np.array(lista2)

In [10]:
%timeit prodotto_np=arr1_np*arr2_np

1.78 ms ± 66.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Ci mette **NOTEVOLMENTE** di meno

Il prodotto di 2 array numpy è a sua volta un array numpy che non creo con un ciclo

In ```numpy``` l'API è pensata il + possibile per scrivere codice nella maniera più semplice possibile, con limitazioni. 

In [16]:
prodotto_NP = arr1_np * arr2_np
prodotto_NP

array([0.00899021, 0.0788819 , 0.09198404, ..., 0.25983349, 0.14213338,
       0.41881651])

In [17]:
#confrontare %timeit np.random con random
%timeit arr1=np.random.random(cicli)

7.04 ms ± 139 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit lista1=[random.random() for i in range(cicli) ]

129 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
np.array?

In [21]:
arr=np.array([1.01,3,2])

In [22]:
arr #upcasting

array([1.01, 3.  , 2.  ])

In [23]:
arr.astype(int) #downcasting

array([1, 3, 2])

In [44]:
interi=np.random.uniform(-1,0,10)
interi

array([-0.92112665, -0.88832856, -0.8391444 , -0.78096847, -0.93984489,
       -0.98498082, -0.18544844, -0.11255198, -0.04156389, -0.11505314])

In [25]:
# Create a length-10 integer array filled with zeros. 
# Inizializza un vettore di tot elementi

np.zeros(10, dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [83]:
interi = np.random.randint(1,10,(20,20))

Esempi di costruttori di array https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html#Creating-Arrays-from-Scratch


In [51]:
arr1_np,arr2_np

(array([0.01063531, 0.09399308, 0.75221731, ..., 0.72360938, 0.14827322,
        0.97883008]),
 array([0.84531721, 0.83923095, 0.12228387, ..., 0.35907977, 0.95859099,
        0.42787458]))

In [52]:
arr1_np/arr2_np

array([0.01258144, 0.11199907, 6.15140253, ..., 2.01517721, 0.1546783 ,
       2.28765651])

In [84]:
interi

array([[4, 2, 9, 4, 1, 4, 9, 8, 5, 8, 2, 5, 1, 3, 9, 8, 6, 9, 7, 7],
       [7, 7, 5, 6, 7, 3, 6, 5, 5, 3, 6, 6, 5, 4, 5, 8, 5, 3, 5, 2],
       [2, 7, 6, 8, 5, 4, 1, 5, 3, 3, 9, 8, 5, 2, 6, 5, 6, 8, 3, 5],
       [3, 6, 2, 2, 5, 8, 3, 2, 9, 2, 8, 9, 1, 6, 7, 1, 8, 5, 9, 7],
       [5, 9, 1, 3, 1, 7, 2, 6, 7, 4, 2, 8, 3, 7, 9, 7, 5, 2, 1, 1],
       [2, 7, 7, 6, 8, 4, 4, 8, 1, 4, 9, 1, 6, 8, 5, 1, 1, 5, 4, 8],
       [7, 5, 3, 2, 8, 2, 9, 5, 2, 6, 7, 9, 1, 8, 8, 6, 8, 1, 1, 9],
       [9, 1, 9, 7, 2, 6, 1, 2, 7, 5, 3, 7, 1, 7, 2, 8, 9, 3, 3, 5],
       [6, 7, 2, 7, 9, 1, 8, 7, 8, 3, 7, 9, 9, 8, 4, 7, 8, 9, 1, 9],
       [1, 1, 4, 9, 5, 7, 6, 6, 3, 7, 6, 7, 6, 4, 9, 8, 4, 2, 2, 7],
       [7, 8, 9, 4, 3, 8, 3, 3, 6, 6, 6, 6, 4, 4, 7, 4, 4, 3, 1, 1],
       [8, 9, 8, 3, 9, 4, 9, 5, 5, 8, 4, 7, 2, 5, 3, 6, 9, 1, 3, 2],
       [7, 7, 1, 1, 9, 7, 6, 1, 4, 8, 5, 4, 1, 4, 2, 7, 9, 3, 8, 2],
       [6, 4, 3, 3, 2, 7, 7, 3, 7, 4, 6, 9, 2, 1, 3, 8, 3, 1, 1, 4],
       [9, 7, 6, 2, 7, 9, 6, 9, 2,

In [85]:
interi**2
#Broadcasting

array([[16,  4, 81, 16,  1, 16, 81, 64, 25, 64,  4, 25,  1,  9, 81, 64,
        36, 81, 49, 49],
       [49, 49, 25, 36, 49,  9, 36, 25, 25,  9, 36, 36, 25, 16, 25, 64,
        25,  9, 25,  4],
       [ 4, 49, 36, 64, 25, 16,  1, 25,  9,  9, 81, 64, 25,  4, 36, 25,
        36, 64,  9, 25],
       [ 9, 36,  4,  4, 25, 64,  9,  4, 81,  4, 64, 81,  1, 36, 49,  1,
        64, 25, 81, 49],
       [25, 81,  1,  9,  1, 49,  4, 36, 49, 16,  4, 64,  9, 49, 81, 49,
        25,  4,  1,  1],
       [ 4, 49, 49, 36, 64, 16, 16, 64,  1, 16, 81,  1, 36, 64, 25,  1,
         1, 25, 16, 64],
       [49, 25,  9,  4, 64,  4, 81, 25,  4, 36, 49, 81,  1, 64, 64, 36,
        64,  1,  1, 81],
       [81,  1, 81, 49,  4, 36,  1,  4, 49, 25,  9, 49,  1, 49,  4, 64,
        81,  9,  9, 25],
       [36, 49,  4, 49, 81,  1, 64, 49, 64,  9, 49, 81, 81, 64, 16, 49,
        64, 81,  1, 81],
       [ 1,  1, 16, 81, 25, 49, 36, 36,  9, 49, 36, 49, 36, 16, 81, 64,
        16,  4,  4, 49],
       [49, 64, 81, 16,  9, 64

In [86]:
np.sin(interi)
#Funzioni universali vedi ufunct docs https://numpy.org/doc/stable/reference/ufuncs.html

array([[-0.7568025 ,  0.90929743,  0.41211849, -0.7568025 ,  0.84147098,
        -0.7568025 ,  0.41211849,  0.98935825, -0.95892427,  0.98935825,
         0.90929743, -0.95892427,  0.84147098,  0.14112001,  0.41211849,
         0.98935825, -0.2794155 ,  0.41211849,  0.6569866 ,  0.6569866 ],
       [ 0.6569866 ,  0.6569866 , -0.95892427, -0.2794155 ,  0.6569866 ,
         0.14112001, -0.2794155 , -0.95892427, -0.95892427,  0.14112001,
        -0.2794155 , -0.2794155 , -0.95892427, -0.7568025 , -0.95892427,
         0.98935825, -0.95892427,  0.14112001, -0.95892427,  0.90929743],
       [ 0.90929743,  0.6569866 , -0.2794155 ,  0.98935825, -0.95892427,
        -0.7568025 ,  0.84147098, -0.95892427,  0.14112001,  0.14112001,
         0.41211849,  0.98935825, -0.95892427,  0.90929743, -0.2794155 ,
        -0.95892427, -0.2794155 ,  0.98935825,  0.14112001, -0.95892427],
       [ 0.14112001, -0.2794155 ,  0.90929743,  0.90929743, -0.95892427,
         0.98935825,  0.14112001,  0.90929743,  

In [89]:
#esercizio:definire ufunct numpy che calcola la rad quad del sin e applicarla ad array interi
np.sqrt(abs(np.sin(interi)))

array([[0.86994396, 0.95357088, 0.64196455, 0.86994396, 0.91731728,
        0.86994396, 0.64196455, 0.99466489, 0.97924679, 0.99466489,
        0.95357088, 0.97924679, 0.91731728, 0.37565943, 0.64196455,
        0.99466489, 0.52859767, 0.64196455, 0.8105471 , 0.8105471 ],
       [0.8105471 , 0.8105471 , 0.97924679, 0.52859767, 0.8105471 ,
        0.37565943, 0.52859767, 0.97924679, 0.97924679, 0.37565943,
        0.52859767, 0.52859767, 0.97924679, 0.86994396, 0.97924679,
        0.99466489, 0.97924679, 0.37565943, 0.97924679, 0.95357088],
       [0.95357088, 0.8105471 , 0.52859767, 0.99466489, 0.97924679,
        0.86994396, 0.91731728, 0.97924679, 0.37565943, 0.37565943,
        0.64196455, 0.99466489, 0.97924679, 0.95357088, 0.52859767,
        0.97924679, 0.52859767, 0.99466489, 0.37565943, 0.97924679],
       [0.37565943, 0.52859767, 0.95357088, 0.95357088, 0.97924679,
        0.99466489, 0.37565943, 0.95357088, 0.64196455, 0.95357088,
        0.99466489, 0.64196455, 0.91731728, 0

In [76]:
np.nan?

In [90]:
complessi=interi.astype(complex)
complessi

array([[4.+0.j, 2.+0.j, 9.+0.j, 4.+0.j, 1.+0.j, 4.+0.j, 9.+0.j, 8.+0.j,
        5.+0.j, 8.+0.j, 2.+0.j, 5.+0.j, 1.+0.j, 3.+0.j, 9.+0.j, 8.+0.j,
        6.+0.j, 9.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 3.+0.j, 6.+0.j, 5.+0.j,
        5.+0.j, 3.+0.j, 6.+0.j, 6.+0.j, 5.+0.j, 4.+0.j, 5.+0.j, 8.+0.j,
        5.+0.j, 3.+0.j, 5.+0.j, 2.+0.j],
       [2.+0.j, 7.+0.j, 6.+0.j, 8.+0.j, 5.+0.j, 4.+0.j, 1.+0.j, 5.+0.j,
        3.+0.j, 3.+0.j, 9.+0.j, 8.+0.j, 5.+0.j, 2.+0.j, 6.+0.j, 5.+0.j,
        6.+0.j, 8.+0.j, 3.+0.j, 5.+0.j],
       [3.+0.j, 6.+0.j, 2.+0.j, 2.+0.j, 5.+0.j, 8.+0.j, 3.+0.j, 2.+0.j,
        9.+0.j, 2.+0.j, 8.+0.j, 9.+0.j, 1.+0.j, 6.+0.j, 7.+0.j, 1.+0.j,
        8.+0.j, 5.+0.j, 9.+0.j, 7.+0.j],
       [5.+0.j, 9.+0.j, 1.+0.j, 3.+0.j, 1.+0.j, 7.+0.j, 2.+0.j, 6.+0.j,
        7.+0.j, 4.+0.j, 2.+0.j, 8.+0.j, 3.+0.j, 7.+0.j, 9.+0.j, 7.+0.j,
        5.+0.j, 2.+0.j, 1.+0.j, 1.+0.j],
       [2.+0.j, 7.+0.j, 7.+0.j, 6.+0.j, 8.+0.j, 4.+0.j, 4.+0.j, 8.+0.j,
   

In [91]:
print(np.sqrt(np.sin(complessi)).round(2))

[[0.  +0.87j 0.95+0.j   0.64+0.j   0.  +0.87j 0.92+0.j   0.  +0.87j
  0.64+0.j   0.99+0.j   0.  +0.98j 0.99+0.j   0.95+0.j   0.  +0.98j
  0.92+0.j   0.38+0.j   0.64+0.j   0.99+0.j   0.  +0.53j 0.64+0.j
  0.81+0.j   0.81+0.j  ]
 [0.81+0.j   0.81+0.j   0.  +0.98j 0.  +0.53j 0.81+0.j   0.38+0.j
  0.  +0.53j 0.  +0.98j 0.  +0.98j 0.38+0.j   0.  +0.53j 0.  +0.53j
  0.  +0.98j 0.  +0.87j 0.  +0.98j 0.99+0.j   0.  +0.98j 0.38+0.j
  0.  +0.98j 0.95+0.j  ]
 [0.95+0.j   0.81+0.j   0.  +0.53j 0.99+0.j   0.  +0.98j 0.  +0.87j
  0.92+0.j   0.  +0.98j 0.38+0.j   0.38+0.j   0.64+0.j   0.99+0.j
  0.  +0.98j 0.95+0.j   0.  +0.53j 0.  +0.98j 0.  +0.53j 0.99+0.j
  0.38+0.j   0.  +0.98j]
 [0.38+0.j   0.  +0.53j 0.95+0.j   0.95+0.j   0.  +0.98j 0.99+0.j
  0.38+0.j   0.95+0.j   0.64+0.j   0.95+0.j   0.99+0.j   0.64+0.j
  0.92+0.j   0.  +0.53j 0.81+0.j   0.92+0.j   0.99+0.j   0.  +0.98j
  0.64+0.j   0.81+0.j  ]
 [0.  +0.98j 0.64+0.j   0.92+0.j   0.38+0.j   0.92+0.j   0.81+0.j
  0.95+0.j   0.  +0.53j 0.81+0.j

In [92]:
np.nan?

### Tensorini!

In [93]:
#Tensoriamoci con numpy!
vet1=np.array([1,2,3])
vet2=np.array([4,5,6])
vet3=np.array([7,8,9])

In [94]:
vet1.ndim

1

In [95]:
vet1.shape

(3,)

In [96]:
#scrivere tre matrici diverse
mat1=np.array([vet1,vet2,vet3])
mat2=np.array([vet2,vet1,vet3])
mat3=np.array([vet3,vet1,vet2])


Così faccio delle matrici

In [97]:
mat1,mat2,mat3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]]),
 array([[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]]))

In [98]:
mat1.ndim

2

In [99]:
mat1.shape

(3, 3)

Adesso faccio un cubotto con le matrici, come ho concatenato i vettori faccio con le matrici

In [100]:
cubo=np.array([mat1,mat2,mat3])

In [101]:
cubo.ndim

3

In [102]:
cubo

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]],

       [[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]]])

In [103]:
cubo.shape

(3, 3, 3)

In [107]:
#stampo elementi con l'accesso classico di python
print(cubo[0][2][2])

#oppure meglio utilizzare la notazione numpy veloce per accedere agli elementi di un array numpy

print(cubo[0,2,2])

9
9


Ricordiamo  ora cosa fosse ```vet1```, per vedere cosa sia il trasposto di un vettorino

In [108]:
vet1

array([1, 2, 3])

In [110]:
vet1.T

array([1, 2, 3])

Non funziona, devo incapsularlo in una matrice

In [111]:
mat=np.array([vet1,])
mat

array([[1, 2, 3]])

In [113]:
mat.shape

(1, 3)

In [114]:
mat.ndim

2

Ne faccio la trasposta:

In [112]:
mat.T

array([[1],
       [2],
       [3]])

In [115]:
mat.T.shape

(3, 1)

In [116]:
mat.T.ndim

2

In [117]:
print(mat)
print(mat.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


Ora così posso fare il prodotto riga per colonna per esempio, o colonna per riga

In [118]:
mat.dot(mat.T)

array([[14]])

In [119]:
mat.T.dot(mat)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
np.random.seed(0)
arr=np.random.randint(0,10,(10**3,10**3))
arr.shape

In [ ]:
print(arr.sum()
,arr.min()
,arr.max()
,arr.mean())

In [ ]:
cubo

In [ ]:
cubo[1][1][1]

In [ ]:
arr

In [ ]:
%timeit arr[0,0]
#utilizzare questa sintassi specifica numpy per array di array ha performance migliori rispetto a sintassi python

In [ ]:
%timeit arr[0][0]

In [ ]:
arr.shape

In [120]:
arr

array([1.01, 3.  , 2.  ])

In [125]:
cubotto = np.random.uniform(0,1,(100,100,100))

In [126]:
print(cubotto)
print('dim', cubotto.ndim)
print('shape', cubotto.shape)

[[[2.65924282e-01 9.02480138e-01 2.21176607e-01 ... 4.60417985e-01
   8.88131842e-01 2.38909668e-01]
  [3.03918139e-01 4.66560651e-01 3.09492489e-01 ... 9.32380549e-01
   6.41721455e-02 2.34710407e-01]
  [6.96279384e-01 3.86708057e-01 4.23956287e-01 ... 4.84464296e-02
   8.24560390e-01 9.85983786e-01]
  ...
  [3.14884231e-01 4.81928877e-01 4.46348020e-02 ... 1.87864600e-01
   3.26237699e-01 3.68461493e-01]
  [9.10315667e-01 3.53692180e-02 1.71373134e-01 ... 2.56242947e-01
   2.36659691e-01 1.56653276e-01]
  [5.83028374e-01 2.23147406e-01 3.76829906e-01 ... 2.71589150e-01
   7.15935249e-01 3.41292357e-01]]

 [[2.81047462e-01 2.18881123e-01 2.64150343e-01 ... 3.97274260e-01
   6.10041075e-02 4.81119832e-02]
  [2.70336806e-01 2.54167846e-02 3.92529654e-01 ... 9.38729694e-01
   2.40048074e-01 2.90089832e-02]
  [3.17167051e-01 4.23030667e-01 5.29900757e-01 ... 9.38783879e-01
   4.37717134e-01 9.56134960e-01]
  ...
  [9.69800370e-01 5.97968976e-01 3.28903470e-01 ... 9.70810097e-02
   4.94895

In [131]:
sottocubotto = cubotto[10:12,3,54:56]
print(sottocubotto)
print('dim', sottocubotto.ndim)
print('shape', sottocubotto.shape)

[[0.14287261 0.55775361]
 [0.56757104 0.55049583]]
dim 2
shape (2, 2)


### Esercizio
1. Definire matrice 10x10 di numeri casuali interi tra {0,1}
1. estrarre prime tre righe
1. estrarre ultime due colonne
1. trovare la media della quarta colonna

In [184]:
#1
matricetta = np.random.randint(0,2,(10,10))
matricetta

array([[0, 0, 1, 1, 1, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 1, 1, 0, 1, 1]])

In [185]:
#2
primeTreRighe = matricetta[0:3]
print(primeTreRighe)

[[0 0 1 1 1 1 0 0 1 0]
 [0 0 0 1 0 0 0 1 1 1]
 [0 0 1 1 1 0 1 0 0 0]]


In [186]:
#3
ultimeDueColonne  = matricetta[:,-2:]
print(ultimeDueColonne)

[[1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]]


In [187]:
#4
avg = np.mean(matricetta[:,3:4])
print(matricetta[:,3:4],'\nMean value = ', avg)

[[1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]] 
Mean value =  0.5


In [ ]:
n_rig,n_col=np.array(arr.shape)//2
n_rig,n_col

In [ ]:
arr[n_rig-1:n_rig+1,n_col-1:n_col+1]

In [ ]:
#estrarre le prime tre colonne
arr[10]

In [ ]:
_.shape

In [ ]:
mat

In [ ]:
mat.T

In [ ]:
MAT=mat+mat_T #broadcasting

In [ ]:
MAT

In [ ]:
MAT+mat_T

More info on broadsting:
https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [ ]:
MAT=np.array([[1,2,3],[4,5,6],[7,8,9]])
MAT

In [ ]:
vet1

In [ ]:
np.dot(vet1,MAT)

In [ ]:
np.dot(MAT,vet1)

In [ ]:
MAT.shape

In [ ]:
vet1.shape

In [ ]:
mat.shape

In [ ]:
np.dot(MAT,mat.T)

In [ ]:
np.dot(mat,MAT).shape

In [ ]:
mat.shape,MAT.shape

In [ ]:
np.dot?

In [ ]:
MAT*MAT

In [ ]:
np.eye(4,dtype=int)

In [ ]:
ID=np.eye(4)
from math import pi
ID*=pi
ID

In [ ]:
np.around(ID,decimals=2)

In [ ]:
ID.round(2)

In [ ]:
a=10
a*=2

In [ ]:
a

In [ ]:
cubo.reshape(-1)

In [ ]:
mat=np.arange(9).reshape((3,3))
mat

Funzioni aggregazione (reduce)

https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html

In [ ]:
mat=MAT
mat

In [ ]:
mat.sum(axis=0)

In [ ]:
mat.sum(axis=1) #sommare lungo una dimensione

In [ ]:
mat2

In [ ]:
mat3

In [ ]:
arr=np.arange(27)
arr

In [ ]:
mat1=arr[:9].reshape((3,3))
mat2=arr[9:18].reshape((3,3))
mat3=arr[18:27].reshape((3,3))

In [ ]:
print(mat1,'\n\n',mat2,'\n\n',mat3)

In [ ]:
mat1=np.ones((3,3),dtype=int)
mat1

In [ ]:
mat2=mat1+1
mat3=mat1+2
mat2,mat3

In [ ]:
TENS=np.concatenate((mat1,mat2,mat3),axis=0).reshape((3,3,3))
TENS

In [ ]:
TENS.sum(axis=0) #sommo lungo le varie dimensions

In [ ]:
TENS.sum(axis=1)

In [ ]:
TENS.sum(axis=2)

In [ ]:
TENS.T

In [ ]:
TENS[0][0][0]

In [ ]:
matrix=np.arange(9).reshape((3,3))
matrix

In [ ]:
matrix.sum()

In [ ]:
sum(matrix)

In [ ]:
matrix.trace()

In [ ]:
np.trace?

In [ ]:
np.linalg?

In [ ]:
import numpy as np
MATRICIONE=np.arange(10**6).reshape((1000,1000))

In [ ]:
MATRICIONE=np.random.randint(1,10,(10000,10000))
MATRICIONE

In [ ]:
MATRICIONE.dot?

In [ ]:
np.random.randint?

In [ ]:
MATRICIONE

In [ ]:
import numpy as np
MATRICIONE=np.arange(10**6).reshape((1000,1000))
matricino=MATRICIONE[:3,:3].copy() #view della matrice grande, ma con copy() diventi oggetto indipendente

In [ ]:
matricino

In [ ]:
matricino[0,0]=123
matricino

In [ ]:
MATRICIONE

In [ ]:
arr=np.array([1,2,3])

In [ ]:
arr[np.newaxis]

In [ ]:
arr=np.arange(18)
arr

In [ ]:
arr1,arr2,arr3=np.split(arr,[2,10])


In [ ]:
arr1,arr2,arr3

In [ ]:
np.split?

In [ ]:
np.split(arr,3)

In [ ]:
mat=np.arange(16).reshape((4,4))
mat

In [ ]:
for m in np.split(mat,2,axis=1):
    print(m,'\n')

In [ ]:
def shift(arr):   #funzione di trasformazione di una lista nella lista shiftata destra di 1
    return np.concatenate((arr[-1:],arr[0:-1]))

In [ ]:
shift([1,2,3,4])

In [ ]:
#Esempio...come implementare un cubo di rubik

class Cubo_Rubik:
    
    def shift(self,arr):   #funzione di trasformazione di una lista nella lista shiftata destra di 1
        import numpy as np
        return np.concatenate((arr[-1:],arr[0:-1]))
    
    def __init__(self):
        import numpy as np
        mat=np.ones((3,3),dtype=int)
        self.facce=np.array([mat*i for i in range(6)]) #creo le facce del cubo
    
    def test_ruota(self): #metodo di test che ruota la prima colonna della prima faccia
        self.facce[:4,:,0]=self.shift(self.facce[:4,:,0])
         
        

In [ ]:
cubo.facce[:4,:,0]

In [ ]:
cubo=Cubo_Rubik()
cubo.facce

In [ ]:
cubo.facce.shape

In [ ]:
cubo.test_ruota()
cubo.facce

In [ ]:
shift(cubo.facce[:4,:,1])

In [ ]:
np.roll(cubo.facce[0:4].reshape((12,3)),3)

In [ ]:
mat=np.arange(1,10).reshape((3,3))
mat

In [ ]:
np.roll(mat,1,axis=0)

In [ ]:
x=np.linspace(0.75,1.25,1000)
x

In [ ]:
#POTENZIALITA' NUMPY: ESEMPIO FINALE

x=np.linspace(0.75,1.25,1000)
y=np.sin(x**2/(x-1))

import matplotlib.pyplot as plt
plt.plot(x,y);

In [ ]:
plt.plot?

In [ ]:
x=np.linspace(0,5,1000)
y=np.linspace(0,5,1000)[:,np.newaxis]
z=np.sin(x)**10+np.cos(10+y*x)*np.cos(x)

In [ ]:
z.shape

In [ ]:
y

In [ ]:
plt.imshow(z,origin='lower',extent=[0,5,0,5],cmap='viridis')
plt.colorbar();

In [ ]:
z[:3,:3]

In [ ]:
plt.imshow?

In [ ]:
z=np.zeros((10,10))
z

In [ ]:
z[::2,::2]=1
z[1::2,1::2]=1

In [ ]:
z

In [ ]:
#ART ATTACK!
plt.imshow(z);


Vediamo ora le tecniche di masking

In [ ]:
np.random.seed(0)
arr=np.random.randint(0,10,10)

In [ ]:
arr

In [ ]:
arr[-1]

In [ ]:
arr[[0,3,-1]] #masking con indici

In [ ]:
arr>4

In [ ]:
arr[_196] #masking con boolean --> filtro

In [ ]:
arr[(arr<=2) | (arr>6)]

In [ ]:
#RANDOM ART ATTACK!
plt.imshow(mat)
plt.colorbar();

In [ ]:
np.random.seed(0)
mat=np.random.randint(0,10,(10,10))

In [ ]:
mat

In [ ]:
sub_mat=np.array([0,9])
print(sub_mat)
mat[sub_mat]

In [ ]:
mat[:,0]<5

In [ ]:
mat[mat[:,0]<5]

In [ ]:
arr=[1,2,3,4,5]
arr=np.array(arr)

In [ ]:
arr[[True,False,False,True,True]]

In [ ]:
mat

In [ ]:
#filtrare dalla matrice tutte e sole le righe la cui somma è minore di 50
mat[mat.sum(axis=1)<50]

In [ ]:
_.sum(axis=1)

In [ ]:
np.sum?

In [ ]:
mat

In [ ]:
mat[mat.sum(axis=1)<50]

In [ ]:
(mat%2==0) | (mat%2==1) & (mat<=5)

In [ ]:
_.shape

In [ ]:
#Esercizio: filtrare da mat tutti i valori dispari maggiori di 5
#usare gli operatori logici bitwise       & =and,  | = or  ,  ^ = xor,  ~ = not

mat[(mat%2==0) | (mat%2==1) & (mat<=5)]

Esercizio riepilogo:
1) Creare una matrice 8x8 di numeri causali interi distribuiti uniformemente tra -10 e 10
2) Filtrare le righe che contengono degli 0
3) Filtrare le colonne il cui valore massimo sia maggiore di 5

In [ ]:
np.random.seed(0)
mat=np.random.randint(-10,11,(8,8))
mat

In [ ]:
mat.prod(axis=1)

In [ ]:
mat.prod(axis=1)!=0

In [ ]:
mat[mat.prod(axis=1)!=0]

In [ ]:
mat.max(axis=0)

In [ ]:
mat.max(axis=0)>5

In [ ]:
mat.T[mat.max(axis=0)<=5].T

Fancy indexing segue regole di bradcasting

In [ ]:
mat

In [ ]:
mat[[0,1],[0,1]]

In [ ]:
mat[[[0],[1]],[0,1]]

In [ ]:
mat[[0,1],[[0],[1]]]